version: '3'

services:
  api:
    image: linkextractor-api:step5-python
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  web:
    image: linkextractor-web:step5-php
    build: ./www
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    depends_on:
      - api

  redis:
    image: redis

  locust:
    image: grubykarol/locust
    container_name: locust_master
    ports:
      - "8089:8089"
    volumes:
      - ../locustfile.py:/locust/locustfile.py:ro
    environment:
      ATTACKED_HOST: http://web
      LOCUST_FILE: /locust/locustfile.py
    depends_on:
      - web