version: '3'

services:
  api:
    image: linkextractor-api:step6-ruby-sem-cache
    build: ./api
    ports:
      - "4567:4567"

  web:
    image: linkextractor-web:step6-php-sem-cache
    build: ./www
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api:4567/api/
    depends_on:
      - api

  locust:
    image: grubykarol/locust
    container_name: locust_master
    ports:
      - "8089:8089"
    volumes:
      - ../locustfile.py:/locust/locustfile.py:ro
    environment:
      ATTACKED_HOST: http://web
      LOCUST_FILE: /locust/locustfile.py
    depends_on:
      - web